/* 1. Campaign Performance by Category
Problem: Analyze how different marketing categories are performing in terms of 
impressions, clicks, leads, orders, and revenue. */
select 
category,
sum(impressions) as total_impressions,
sum(clicks) as total_clicks,
sum(leads) as total_leads,
sum(orders) as total_orders,
sum(revenue) as total_revenue
from marketing_data
group by category
order by total_revenue desc;

/* 2. Conversion Rate by Campaign
Problem: Calculate the conversion rate (orders/clicks) for each campaign to 
understand the effectiveness of campaigns in driving actual purchases. */
select
campaign_id,
campaign_name,
sum(orders) as total_order,
sum(clicks) as total_clicks,
(sum(orders)/sum(clicks)) * 100 as conversion_rate
from marketing_data
group by campaign_id, campaign_name
order by conversion_rate desc;

/*  3. Cost Per Lead by Category
Problem: Determine the Cost Per Lead (market_spent/leads) for 
different categories to see which category brings in the most cost-effective leads. */
select
category,
sum(market_spent) as total_market_spent,
sum(leads) as total_leads,
round((sum(market_spent)/sum(leads)),2) as cost_per_lead
from marketing_data
group by category
order by cost_per_lead asc;

/* 4. Revenue per Campaign Over Time
Problem: Analyze total revenue generated by each campaign over time to understand trends in campaign effectiveness. */
select 
campaign_id,
campaign_name,
campaign_date as campaign_day,
sum(revenue) as total_revenue
from marketing_data
group by campaign_id, campaign_name, campaign_day
order by campaign_day asc;

/* 5. Market Spend vs Revenue (ROI) per Campaign
Problem: Compare market spend with revenue to calculate ROI (Return on Investment) for each campaign. */
select 
campaign_id,
campaign_name,
round(sum(market_spent),2) as total_spent,
sum(revenue) as total_revenue,
round((sum(revenue) -sum(market_spent))/sum(market_spent)*100,2)  as ROI
from marketing_data
group by campaign_id, campaign_name
order by ROI desc;

/* 6. Top Campaigns by Click-Through Rate (CTR)
Problem: Identify the top campaigns by Click-Through Rate (CTR) (clicks/impressions) 
to see which campaigns are best at driving traffic. */
select 
campaign_id,
campaign_name,
sum(clicks) as total_click,
sum(impressions) as total_impressions,
(sum(clicks)/sum(impressions))*100 as CTR
from marketing_data
group by campaign_id, campaign_name
order by CTR desc;

/* 7. Lead-to-Order Conversion Rate by Campaign
Problem: Calculate the Lead-to-Order Conversion Rate (orders/leads) 
for each campaign to identify how well leads are converting into sales. */
select 
campaign_id,
campaign_name,
sum(leads) as total_leads,
sum(orders) as total_orders,
(sum(orders)/sum(leads))*100 as lead_to_order_conversion_rate
from marketing_data
group by campaign_id, campaign_name
order by lead_to_order_conversion_rate desc;

/* 8. Campaign Revenue Breakdown by Day of Week
Problem: Analyze how revenue generation varies by day of the week across all campaigns. */
select 
dayname(STR_TO_DATE(campaign_date, '%d-%m-%Y')) as day_of_week,
sum(revenue) as total_revenue
from marketing_data
group by day_of_week
order by  FIELD(day_of_week, 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');

/* 9. CPC (Cost Per Click) by Category
Problem: Calculate Cost Per Click (CPC) (market_spent/clicks) for each category to analyze cost-efficiency. */
select 
category,
round(sum(market_spent),2) as total_market_spent,
sum(clicks) as total_clicks,
round((sum(market_spent)/sum(clicks))*100,2) as CPC
from marketing_data
group by category
order by CPC asc;

/* 10. Campaigns with Highest Revenue Per Order
Problem: Identify campaigns that have the highest revenue per order (revenue/orders). */
select 
campaign_id,
campaign_name,
sum(revenue) as total_revenue,
sum(orders) as total_orders,
round((sum(revenue)/sum(orders)),2) as revenue_per_order
from marketing_data
group by campaign_id, campaign_name
order by revenue_per_order desc;

/* 11. Market Spend Efficiency (Revenue/Market Spend) by Campaign
Problem: Analyze market spend efficiency by comparing revenue with market spend for each campaign. */
select 
campaign_name,
sum(revenue) as total_revenue,
round(sum(market_spent),2) as total_market_spent,
round(sum(revenue)/sum(market_spent),2) as revenue_to_spent_ratio
from marketing_data
group by campaign_name
order by revenue_to_spent_ratio desc;

/* 12. Revenue by Campaign Over Different Periods (Monthly/Quarterly)
Problem: Analyze monthly or quarterly trends in revenue across campaigns. */
select 
campaign_name,
year(STR_TO_DATE(campaign_date, '%d-%m-%Y')) as year,
month(STR_TO_DATE(campaign_date, '%d-%m-%Y')) as month,
sum(revenue) as total_revenue
from marketing_data
group by campaign_name, year, month
order by year, month;

/* 13. Leads to Revenue Efficiency by Campaign
Problem: Compare how efficiently leads are translating to revenue for each campaign. */
select 
campaign_name,
sum(leads) as total_leads,
sum(revenue) as total_revenue,
round(sum(revenue)/sum(leads),2) as revenue_per_lead
from marketing_data
group by campaign_name
order by revenue_per_lead desc;

/* 14. Campaign Overlap Analysis
Problem: Analyze whether campaigns running during the same period 
show overlapping performance in terms of leads or revenue. */
select 
campaign_name,
campaign_date,
sum(leads) as total_leads,
sum(revenue) as total_revenue
from marketing_data
group by campaign_name, campaign_date
order by campaign_date asc;